### ISSUE TITLE
Dynamics NAV 2017 : Report preview does not work and hangs web client

### ISSUE THREAD

**Issue by maksym-ch** [ajkauffmann/DynamicsNAV#3]
Hi, I have the following configuration :
- Dynamics NAV 2017 build 21440
- Windows Server 2012R2

1. Open web client. 
2. Go to Sales Invoices
3. Create/ Open Sales Invoice
4. Click Test Report - Preview
5. Web Client hangs, nothing is shown

**Event Viewer throws the following error (printer is not installed):**
Error accessing Website Microsoft Dynamics NAV 2017 Web Client
Raw Url: /DynamicsNAV100/WebClient/ReportPreview.aspx?i=CC1&u=1564476702568&company=CRONUS%20EspaÃ±a%20S.A.&bookmark=47%3bJAAAAACLAgAAAAJ7%2f1QAMQAwADEAMAAxADIAMQA5ADAAMAAwADAAMAA2&page=43&IsDlg=1
Url: http://localhost:8080/DynamicsNAV100/WebClient/ReportPreview.aspx?i=CC1&u=1564476702568&company=CRONUS%20EspaÃ±a%20S.A.&bookmark=47%3bJAAAAACLAgAAAAJ7%2f1QAMQAwADEAMAAxADIAMQA5ADAAMAAwADAAMAA2&page=43&IsDlg=1
Type: System.Drawing.Printing.InvalidPrinterException
Message: No printers are installed.
StackTrace:
   at System.Drawing.Printing.PrinterSettings.GetHdevmodeInternal(String printer)
   at System.Drawing.Printing.PrinterSettings.GetHdevmode()
   at System.Drawing.Printing.PageSettings.GetPaperSize(IntPtr modeHandle)
   at System.Drawing.Printing.PageSettings.get_PaperSize()
   at Microsoft.Reporting.ReportViewerUtils.DeepClonePageSettings(PageSettings pageSettings)
   at Microsoft.Reporting.WebForms.ReportViewer.SetPageSettings(PageSettings pageSettings)
   at Microsoft.Dynamics.Framework.UI.Web.ReportPreviewFormControl.SetPrinterSettings(ReportViewer nativeControl, ReportControl reportControl)
   at Microsoft.Dynamics.Framework.UI.Web.ReportPreviewFormControl.CreateReportViewer(ReportControl reportControl)
   at Microsoft.Dynamics.Framework.UI.Web.ReportPreviewFormControl.CreateReportContent(ReportControl reportControl)
   at Microsoft.Dynamics.Framework.UI.Web.ReportPreviewFormControl.OnLoadCore(EventArgs e)
   at Microsoft.Dynamics.Framework.UI.Web.WebEventExecutor.<>c__DisplayClass6_0.<Execute>b__0()
   at Microsoft.Dynamics.Framework.UI.Web.WebEventExecutor.ExecuteCore[T](Func`1 webEvent, Func`1 condition)

**Event Viewer throws the following error (printer installed):**
Error accessing Website Microsoft Dynamics NAV 2017 Web Client
Raw Url: /DynamicsNAV100/WebClient/ReportPreview.aspx?i=1B03&u=1564481429500&company=CRONUS%20EspaÃ±a%20S.A.&page=43&IsDlg=1
Url: http://localhost:8080/DynamicsNAV100/WebClient/ReportPreview.aspx?i=1B03&u=1564481429500&company=CRONUS%20Espa%C3%B1a%20S.A.&page=43&IsDlg=1
Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
StackTrace:
   at Microsoft.Dynamics.Framework.UI.Web.ReportPreviewFormControl.OnLoadCore(EventArgs e)
   at Microsoft.Dynamics.Framework.UI.Web.WebEventExecutor.<>c__DisplayClass6_0.<Execute>b__0()
   at Microsoft.Dynamics.Framework.UI.Web.WebEventExecutor.ExecuteCore[T](Func`1 webEvent, Func`1 condition)

The following solutions have not helped:
- install printer and make default under NAV Service Account
- change web cliebnt authorization to NavUserPassword
- change account for NAV Web Client Application poll

Could you please advise how to fix it?

Thank you in advance.

**Comment by ajkauffmann** [comment]
I'm sorry, but I have no idea how to solve this issue.
Please use Microsoft support to get help with this.

**Comment by maksym-ch** [comment]
Thank for quick response.
